// Code generated by sqlc. DO NOT EDIT (manually authored as a sqlc-equivalent stub).
// source: query.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

// DBTX 는 *sql.DB 와 *sql.Tx 가 모두 만족하는 최소 인터페이스이다.
// sqlc 가 생성하는 표준 구조와 동일하며, 트랜잭션 분기 시 Queries 를 tx 로 전환할 수 있게 해 준다.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// New 는 DBTX 를 감싼 Queries 핸들을 생성한다.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Queries 는 sqlc 가 생성하는 쿼리 핸들 컬렉션이다.
type Queries struct {
	db DBTX
}

// WithTx 는 동일한 Queries 메서드 셋을 트랜잭션 위에서 실행할 수 있도록
// 새 Queries 인스턴스를 반환한다.
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}
