// Code generated by sqlc. DO NOT EDIT (manually authored as a sqlc-equivalent stub).

package sqlcdb

import (
	"encoding/json"
	"time"
)

// LlmProvidersProviderType 은 ENUM('LOCAL','EXTERNAL') 컬럼의 Go 표현이다.
type LlmProvidersProviderType string

const (
	LlmProvidersProviderTypeLOCAL    LlmProvidersProviderType = "LOCAL"
	LlmProvidersProviderTypeEXTERNAL LlmProvidersProviderType = "EXTERNAL"
)

// Scan 은 sql.Scanner 구현으로, ENUM 컬럼을 안전히 역직렬화한다.
func (e *LlmProvidersProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LlmProvidersProviderType(string(s))
	case string:
		*e = LlmProvidersProviderType(s)
	case nil:
		*e = ""
	}
	return nil
}

// LlmProvider 는 llm_providers 테이블의 Go 표현이다.
// sqlc override 에 따라:
//   - is_active (TINYINT(1)) → bool
//   - config_json (JSON)     → json.RawMessage
type LlmProvider struct {
	ID           int64                    `json:"id"`
	Name         string                   `json:"name"`
	IsActive     bool                     `json:"is_active"`
	ProviderType LlmProvidersProviderType `json:"provider_type"`
	ConfigJson   json.RawMessage          `json:"config_json"`
	CreatedAt    time.Time                `json:"created_at"`
	UpdatedAt    time.Time                `json:"updated_at"`
}
