// Code generated by sqlc. DO NOT EDIT (manually authored as a sqlc-equivalent stub).
// source: query.sql

package sqlcdb

import (
	"context"
	"encoding/json"
)

// ---------------------------------------------------------------------------
// GetActiveProvider
// ---------------------------------------------------------------------------

const getActiveProvider = `-- name: GetActiveProvider :one
SELECT id, name, is_active, provider_type, config_json, created_at, updated_at
FROM llm_providers
WHERE is_active = 1
LIMIT 1`

func (q *Queries) GetActiveProvider(ctx context.Context) (*LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, getActiveProvider)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.ProviderType,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &i, nil
}

// ---------------------------------------------------------------------------
// GetProviderByID
// ---------------------------------------------------------------------------

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, is_active, provider_type, config_json, created_at, updated_at
FROM llm_providers
WHERE id = ?`

func (q *Queries) GetProviderByID(ctx context.Context, id int64) (*LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByID, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.ProviderType,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &i, nil
}

// ---------------------------------------------------------------------------
// ListProviders
// ---------------------------------------------------------------------------

const listProviders = `-- name: ListProviders :many
SELECT id, name, is_active, provider_type, config_json, created_at, updated_at
FROM llm_providers
ORDER BY id ASC`

func (q *Queries) ListProviders(ctx context.Context) ([]*LlmProvider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := []*LlmProvider{}
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.ProviderType,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ---------------------------------------------------------------------------
// CreateProvider
// ---------------------------------------------------------------------------

const createProvider = `-- name: CreateProvider :execresult
INSERT INTO llm_providers (name, is_active, provider_type, config_json)
VALUES (?, ?, ?, ?)`

// CreateProviderParams 는 CreateProvider 의 입력 파라미터 묶음이다.
type CreateProviderParams struct {
	Name         string                   `json:"name"`
	IsActive     bool                     `json:"is_active"`
	ProviderType LlmProvidersProviderType `json:"provider_type"`
	ConfigJson   json.RawMessage          `json:"config_json"`
}

// CreateProvider 는 INSERT 후 생성된 ID 를 알아내고, 같은 행을 SELECT 하여
// AUTO_INCREMENT id 와 DB 가 채운 타임스탬프를 포함한 LlmProvider 를 반환한다.
// (sqlc :execresult 의 결과를 활용한 동등 동작)
func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (*LlmProvider, error) {
	res, err := q.db.ExecContext(ctx, createProvider,
		arg.Name,
		arg.IsActive,
		arg.ProviderType,
		[]byte(arg.ConfigJson),
	)
	if err != nil {
		return nil, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return nil, err
	}
	return q.GetProviderByID(ctx, id)
}

// ---------------------------------------------------------------------------
// DeactivateAllProviders  (트랜잭션용)
// ---------------------------------------------------------------------------

const deactivateAllProviders = `-- name: DeactivateAllProviders :exec
UPDATE llm_providers SET is_active = 0 WHERE is_active = 1`

func (q *Queries) DeactivateAllProviders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deactivateAllProviders)
	return err
}

// ---------------------------------------------------------------------------
// ActivateProviderByID  (트랜잭션용)
// ---------------------------------------------------------------------------

const activateProviderByID = `-- name: ActivateProviderByID :execrows
UPDATE llm_providers SET is_active = 1 WHERE id = ?`

// ActivateProviderByID 는 영향받은 행 수를 반환하여,
// 호출자가 0 행이면 ErrProviderNotFound 로 분기할 수 있게 한다.
func (q *Queries) ActivateProviderByID(ctx context.Context, id int64) (int64, error) {
	res, err := q.db.ExecContext(ctx, activateProviderByID, id)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// ---------------------------------------------------------------------------
// UpdateProviderConfig
// ---------------------------------------------------------------------------

const updateProviderConfig = `-- name: UpdateProviderConfig :exec
UPDATE llm_providers SET config_json = ? WHERE id = ?`

// UpdateProviderConfigParams 는 config_json 갱신 파라미터 묶음이다.
type UpdateProviderConfigParams struct {
	ConfigJson json.RawMessage `json:"config_json"`
	ID         int64           `json:"id"`
}

// UpdateProviderConfig 는 영향받은 행 수를 반환하여,
// 호출자가 0 행이면 ErrProviderNotFound 로 분기할 수 있게 한다.
func (q *Queries) UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) (int64, error) {
	res, err := q.db.ExecContext(ctx, updateProviderConfig, []byte(arg.ConfigJson), arg.ID)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// ---------------------------------------------------------------------------
// DeleteProvider
// ---------------------------------------------------------------------------

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM llm_providers WHERE id = ?`

// DeleteProvider 는 영향받은 행 수를 반환하여,
// 호출자가 0 행이면 ErrProviderNotFound 로 분기할 수 있게 한다.
func (q *Queries) DeleteProvider(ctx context.Context, id int64) (int64, error) {
	res, err := q.db.ExecContext(ctx, deleteProvider, id)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
